### PR TITLE
Fix reddit button on image search page

### PR DESCRIPTION
**Pull request by tadwohlrapp**
Hey @marioortizmanero, it's Tad again with another little fix :)

The Reddit button was missing on the image search page, because of the TrustedTypes policy implemented there (which is preventing 'innerHtml' and was throwing an error for the user script).

Also the image search page has different markup with different css classes, so now there's a check for which page the user is on (image search or regular search) and classes are queried/added accordingly.

### CODE REVIEW

**Comment by marioortizmanero** [comment]
Hey Tad, thank you very much for the contribution!

Unfortunately, I tried to use your changes and they give me this warning, and no reddit button is displayed in neither of the google search pages:

image

Any idea of what that could be? It is right that no `trustedTypes` seems to be defined

**Comment by tadwohlrapp** [comment]
Oh, right! I forgot about Firefox, which doesn't support `trustedTypes`:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types

Fixed it now  :)

**Comment by marioortizmanero** [comment]
One last thing: in the regular search page, the button is added to the left of the "More` button. But in the images page, it's to the right. It's not too important but it'd be nice to have them both to the left, if possible.

image

**Comment by tadwohlrapp** [comment]
Right. That bugged me as well, but I thought it would go unnoticed by anyone else, haha.
Anyways, that as well should be fixed now. Let me know if it works for you and if there's anything else.

**Comment by marioortizmanero** [comment]
Works perfectly! Thanks a bunch for the PR :)

**Pull request merged**
